version: '3.8'  # Or the version you prefer

services:
  frontend:
    build: ./frontend   
    ports:
      - "3000:3000"     
    depends_on:
      - backend 
  
  backend:
    build: ./backend    
    ports:
      - "8080:8080"     
    environment:       
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/documents_db 
    depends_on:
      - db
  
  db:
    image: postgres:14   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=documents_db  
    volumes:             
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
