export const ACTION = {
  SET_LOADING: 'SET_LOADING',
  MOVE_DOCUMENT: 'MOVE_DOCUMENT',
  SET_DOCUMENTS: 'SET_DOCUMENTS',
  SET_SELECTED_IMAGE: 'SET_SELECTED_IMAGE',
  SET_LAST_SAVE: 'SET_LAST_SAVE'
}